---
# practicing to iterate over lists defined in playbook and in separate file

- name: test
  hosts: all
  become: true
  vars: 
    users_list: [bart, fred, henk]
  vars_files:
    - uservars.yml  
  tasks:
    - name: add users
      user:
        name: "{{ item }}"
        state: present 
        groups: "wheel"
      loop: "{{ myusers }}"
        
